language: sml
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes smlnj
install:
  - git submodule init
  - git submodule update --init --recursive
script:
  - make smlnj
  - make test

